apiVersion: v1
kind: ReplicationController
metadata:
  name: <App rc>
  namespace: <Namespace>
  labels:
    app: <App name>
    type: <App type>
spec:
  template:
    metadata: 
      name: <Pod name>
      labels:
        app: <App name>
        type: <App type>
    spec:
      containers:
        - image: nginx
          name: nginx
        - image: redis
          name: redis
  replicas: 3