apiVersion: networking.k8s.io/v1
kind: NetworkingPolicy
metadata: 
  name: db-policy
spec:
  podSelector:
    matchLabels:
      role: db

  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
      - podSelector:
          matchLabels:
            name: api-pod
        namespaceSelector:
          matchLabels:
            name: prod
      ports:
        - protocol: TCP
          port: 3306
