apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster-101
  region: ap-southeast-1

vpc:
  subnets:
    private:
      ap-southeast-1a: { id: subnet-0bf434446a49496c7 }
      ap-southeast-1b: { id: subnet-009198aef5b591e73 }