apiVersion: v1
kind: Pod
metadata:
  name: web-app
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - mountPath: /var/log/app-log
          name: vol-app-log
  
  volumes:
    - name: vol-app-log
      persistanceVolumeClaim:
        claimname: myclaim
    - name: vol-host-app-log
      hostPath:
        path: /app-log
        type: Directory