apiVersion: v1
kind: PersistentVolumes
metadata:
  name: pv-uat-mox-weblog
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  #hostPath:
    #path: /tmp/data
  awsElasticBlockStore:
    volumeID: <volume-id>
    fsType: ext4