apiVersion: v1
kind: PersistantVolumeClaim
metadata:
  name: pvc-app-log
spec:
  resources:
    requests:
      storage: 500Mi
  selector:
    matchLabels:
      name: pv-app-log
  accessModes:
    - ReadWriteMany