
apiVersion: networking.k8s.io/v1
kind: networking
metadata:
  name: db-policy
spec:
  podSelector:
    matchLabels:
      role: db 
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSlector:
            matchLabels:
              role: db
      ports:
        protocols: TCP
        ports: 3306
  egress:
    - to:
        ipBlock:
          cidr: 192.168.1.1/32
      ports:
        protocols: TCP
        ports: 3306