apiVersion: apps/v1
kind: Deployment
metadata:
  name: <Deployment name>
  namespace: <Namespace name>
  labels:
    app: <Deployment app name>
    type: <Deployment type>
spec:
  template:
    metadata:
      name: <Pod name>
      labels:
        app: <Pod app name>
        type: <Pod app type>
    spec:
      containers:
        - name: nginx 
          image: nginx
          resources:
            requests:
              memory: <Number of mem>
              cpu: <Number of vCPU>
            limits:
              resources:
                memory: <Number of mem>
                cpu: <Number of vCPU>
        - name: redis
          image: redis
          resources:
            requests:
              memory: <Number of mem>
              cpu: <Number of cpu>
            limits:
              memory: <Number of mem>
              cpu: <Number of cpu>
  replicas: 3
  selector:
    matchLabels:
      type: <Pod app type>