apiVersion: apps/v1
kind: Deployment
metadata:
  name: <Deployment name>
  namespace: <Namespace name>
  labels:
    app: <Deployment app name>
    type: <Deployment type>
spec:
  template:
    metadata:
      name: <Pod name>
      labels:
        app: <Pod app name>
        type: <Pod app type>
    spec:
      containers:
        - name: nginx 
          image: nginx
        - name: redis
          image: redis
  replicas: 3
  selector:
    matchLabels:
      type: <Pod app type>